### ISSUE TITLE
Contact tab content display issues

### ISSUE THREAD

**Issue by jeremyBass** [washingtonstateuniversity/WSU-spine#102]
On `.organization-name` for css rule `#spine .spine-contact .organization-name` needs to have `white-space: nowrap;` removed.  Having it where with a unit name of `The Campaign for Washington State University` produces this.
![2014-07-27_1121](https://cloud.githubusercontent.com/assets/43837/3714754/1a9ee60e-15bb-11e4-81a9-893a88933280.png)

Removing it corrects it, producing 
![2014-07-27_1124](https://cloud.githubusercontent.com/assets/43837/3714759/51a7f58c-15bb-11e4-9ea2-00efd4f55ba7.png)

There is also a note here that I think we need to set the docs up to say that `if your address has a Suite it is better to provide a <br/> between`.  Conversely we could auto count characters to auto correct the display.  It wouldn't be overreaching really as we make the area anyways, but we would have better display.  Simple rules like "on street address if `,` exists then insert <br/> " for example.  Areas I see as issue here are

1. Vanity phone numbers
1. suite and appartments
1. phone number extensions

Example issues and corrections are as follows.

    `255 E. Main Street, Suite 301`

ends up looking like 

![2014-07-27_1132](https://cloud.githubusercontent.com/assets/43837/3714771/5809cdbe-15bc-11e4-9800-a2a7f9da4062.png)

But if we auto break on `,` for street addresses only we can correct the odd display since we know that the `,` is used for `apt` or `suite` designations, we can produce
![2014-07-27_1135](https://cloud.githubusercontent.com/assets/43837/3714777/e38e382a-15bc-11e4-8d34-3d52162fe524.png)

We can use the fact that addresses and contact information has to have the same pattern to be understandable to other in order help correct the display.  We can count on adding that break with out worry.  I believe our best bet is to do a set of rules to insert breaks, and also count characters to invoke a  break.  We would just provide a set of regex patterns so is something we can overload and not lock the end user in to this auto feature.

**Comment by jeremyfelt** [comment]
I am no longer able to reproduce the originally reported issue with wrapping text in `.organization-name`.
