### ISSUE TITLE
Template helper functions.

### ISSUE THREAD

**Issue by jeremyBass** [washingtonstateuniversity/WSU-spine#103]
We have some utility style functions that helps the spine framework produces it's display.  In order to address #102 we'll need to add a few more helper functions.  I believe there are a few more things that we can add that are content based and expose it for usage.  The goal would be to identify content display conditions that we want to look consistent by default across all sites.  One items could be how excerpts are displayed,

```
$('p.truncate').spine( 'truncate' , { 
           'end' : '...' ,
            'limit' : 250
 });
```

The is just an example, and may not be one we want, but the thought is that we identify items that would be helpful to the framework, but also to the implementer in controlling  content display.  This would fill in a gap where it's not really a plugin but it is out side the area of manipulation by default for the spine framework.

Here is one helper I have to put in the central store, but is something that would be good to have access to in other sites.  I already know that there will be some planed sits that will be leading to the WSU Marketplace and they will be displaying prices, so 

a currency formatter (again example not final)
```
$.spine.currency= function(number){
	var formater = new Intl.NumberFormat('en-US', {
		style: 'currency',
		currency: 'USD',
		minimumFractionDigits: 2,
	});
	return formater.format(number);
};

 //current usage
$('.price').html( $.spine.currency( 1+1 ) );

```

The point is to just be more mindful of utilities we can provide.  A starter list of content display areas that could benefit from added helper utilities are

1. phone numbers
1. addresses
1. excerpts
1. currency
1. fluid image 
1. lazyload image
1. retina image replacement

These would be a light weight low code addition to the framework, which many other frameworks offer.

**Comment by jeremyfelt** [comment]
I'm going to close this out for now. We should determine in the future if non-brand/Spine related functionality is necessary in the framework and then tackle each need individually as it comes up.
