### ISSUE TITLE
External dependencies and tracking

### ISSUE THREAD

**Issue by wjbonner** [washingtonstateuniversity/WSU-spine#15]
The AddThis widget adds an unnecessary external dependency and is known to cause latency and timeouts.  Worse, AddThis creates third party tracking cookies for ScoreCardResearch, which is owned by comscore.  Part of the AddThis latency and timeouts stems from the ScoreCardResearch resources sometimes being unavailable or slow to load (see http://support.addthis.com/customer/portal/questions/3037805-scorecard-research).

Regardless of external dependencies (which I again say are bad for a global template), the tracking cookies are unacceptable.  If you clear your cookies and then load a page using this template you will find two new cookies with URL scorecardresearch.com named UID and UIDR.  Do I need to say any more about how this is terrible for a global university template?

**Comment by natejacobson** [comment]
This can be closed now that we are using a "Web Intents" based approach to sharing which is low-overhead and free of cookies.
