### ISSUE TITLE
Revisit icon behavior when bringing up spine modals

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSU-spine#174]
* Should the "X" remain off hover?
* Should clicking anywhere on the page remove the modal?

![search-x](https://cloud.githubusercontent.com/assets/286171/5147711/96171a06-716c-11e4-9ba2-a728df39e8cb.gif)

**Comment by jeremyBass** [comment]
@natejacobson added this, and is in the current version.  marking this closed

**Comment by jeremyfelt** [comment]
Persisting "x" addressed in e7cfe6b7bfad9b8116cf7a7 via #265.
