### ISSUE TITLE
Eliminate spine transparency at less than large layouts

### ISSUE THREAD

**Issue by natejacobson** [washingtonstateuniversity/WSU-spine#185]
By default, opacity of the spine should be restored to 100% once the spine is shelved because when unshelved, it will lay over content that will inevitably bleed through and interfere with the spine nav and links.

**Comment by jeremyfelt** [comment]
This appears to have been fixed in 00207df9474da5 when `.spine-full` was introduced and added to `#glue:before` for specificity. See #318.
