### ISSUE TITLE
Media queries for cropped Spine misaligned

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSU-spine#188]
Excuse the swarm of screenshots... :)

990px:
![990](https://cloud.githubusercontent.com/assets/286171/5368760/cacd368a-7fbe-11e4-82d9-323f19a95949.png)

989px:
![989](https://cloud.githubusercontent.com/assets/286171/5368759/c9480736-7fbe-11e4-911f-49e57692a46a.png)

988px:
![988](https://cloud.githubusercontent.com/assets/286171/5368758/c70a39bc-7fbe-11e4-850d-4586b0c7ccaf.png)

792px:
![792](https://cloud.githubusercontent.com/assets/286171/5368757/c524d76a-7fbe-11e4-8828-588fa6aacf27.png)

791px:
![791](https://cloud.githubusercontent.com/assets/286171/5368755/c1f59322-7fbe-11e4-96ff-a2fc9f8fc6c0.png)

* At `990px`, styles for `.cropped` are still available, so the nav for the Spine is hidden.
* At `989px`, the WordPress admin bar moves to the bottom, leaving a blank at the top.
    * This should likely be fixed in the Spine Parent Theme
* At `988px`, the gap left by the admin bar disappears. Again, likely fix is in the theme.
* From `989px to `792px`, the "cropped" spine is shown in full.
* At `791px`, the tablet/mobile Spine is added.

It seems like the fix would be to modify [the cropped media query](https://github.com/washingtonstateuniversity/WSU-spine/blob/1f2162e4a730253eb05e94e3b28899695a80d61c/styles/sass/spine/_cropped.scss#L5) to target `792px` instead of `990px`.

**Comment by richardblink** [comment]
What is the status of this, since It missed the last couple versions?  This is the exact scenario we are running into on our new layout.

Thanks

**Comment by jeremyfelt** [comment]
I believe this is fixed after the work done to refactor how mobile is detected in #318. It can be tested in the `develop` branch now, which is being prepped for release in the near future.
