### ISSUE TITLE
Correct missing menu button backgroung-image on resize

### ISSUE THREAD

**Issue by jeremyBass** [washingtonstateuniversity/WSU-spine#216]
In some browsers, I have confirmed it in both Chrome and IE 11, if you start out with a full screen and then resize the window so it ends up in the mobile state, the menu icon will not show.  The case is that when it goes from `display:none` to `display:block` for what ever reason the browsers don't function correctly and show the background image.  

![fc2f087606e52e274fb2777c3a678d7c](https://cloud.githubusercontent.com/assets/43837/5495985/7fe603fe-86b7-11e4-8a8b-839589f9694d.gif)

This happens because the CSS although is written in [spec](http://www.w3.org/TR/CSS2/syndata.html#value-def-uri) and the initial browser parsing is not applied because the item is out of the DOM scope since it's `display:none`. I can force the browser reparse of the css by turning the property on and off

![4e184477ff4c445b1b4ca3762b328d6a](https://cloud.githubusercontent.com/assets/43837/5495894/afaad30e-86b6-11e4-85aa-7014658e94d6.gif)

 This is so very nit picky here, but the browsers seem to freak out that we are using single quotes not double or even none.  I have tested these changes:

**from:**
```scss
background: transparent url('#{$locality}/icons/menu.svg') 20px center no-repeat;
```

**to:**
```scss
background: transparent url("#{$locality}/icons/menu.svg") 20px center no-repeat;
```
or
```scss
background: transparent url(#{$locality}/icons/menu.svg) 20px center no-repeat;
```

The changes work to correct the issue over all.  We just need to alter https://github.com/washingtonstateuniversity/WSU-spine/blob/develop/styles/sass/_column.scss#L128 and it'll correct the issue.

**Comment by natejacobson** [comment]
Addressed, hopefully solved, in #275.
