### ISSUE TITLE
general js code refinement `$.ui.spine.prototype.setup_spine()`

### ISSUE THREAD

**Issue by jeremyBass** [washingtonstateuniversity/WSU-spine#223]
I was just looking over what major changes we have and saw a quick refinement we can do.  Just stashing it to so it's not forgotten while conflicting edits are still in the PR pool.

[@L165](https://github.com/washingtonstateuniversity/WSU-spine/blob/develop/scripts/ui.spine.framework.js#L165)
```js
			ele_class=size_xlarge;
			if(current_width >= 990) {
				ele_class=size_large;
			} else if/* etc.*/

```
can drop 3 lines and one condition loop by setting `ele_class="";` to `ele_class=xlarge;` since it's never `""`

**Comment by jeremyfelt** [comment]
I finally started poking at this today. If we remove the `>= 1188` conditional and set the default to `size_xlarge`, the first rule - `>=990` - will match and overwrite with `size_large`. I was able to make a few other adjustments to that area that hopefully clarify/simplify a bit.
