### ISSUE TITLE
Cmd-click does not open all links in new tab

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSU-spine#225]
This was reported by Joyce a long while ago and we were never able to sort it out.

* I can reproduce it on the Provost site and others in OSX Chrome.
* If I cmd-click "Strategic Plan" in the offsite menu, it opens in the current tab.
* A cmd-click on "Initiatives" opens in a new tab as expected.

I'm not sure that this is a Spine issue, but it's the most relevant place to track it. I had thought at one point it could be related to analytics scripting, so that's where I'll dig next.

**Comment by jeremyfelt** [comment]
The same issue happens on creamery.wsu.edu for the "Order Online" external link in the Cougar Cheese navigation area. Chrome 40 on OSX.

**Comment by jeremyfelt** [comment]
Not all links are in the Spine - the related links here don't work either - http://creamery.wsu.edu/related-links/

The PDF in the navigation does work.

**Comment by jeremyBass** [comment]
Can you point out which ones? I just tested that page and every link I hit works in Chrome on Windows

**Comment by jeremyBass** [comment]
aw check that .. the crt click thing, that is the tracker, which is corrected with the next update

**Comment by jeremyBass** [comment]
This was not a spine level issue, it was from the tracker, which has been resolved on that end and would correct the creamery site via the update to the wsuwp-analytic plugin's update.

**Comment by jeremyfelt** [comment]
Confirmed :+1:
