### ISSUE TITLE
Override Dafault Signature from Spine Colors

### ISSUE THREAD

**Issue by Toreybearly** [washingtonstateuniversity/WSU-spine#228]
When using crimson for the #spine color scheme, the signature is defaulted to the WSU base signature.  The traditional method of changing the signature does not work and the guide states "Custom versions of each campus signature are used automatically with some colors." Is there anyway to override this and use the .globalcampus-signature?

**Comment by natejacobson** [comment]
If I understand your question correctly, @Toreybearly, I'm guessing that there is an error in execution. In my tests, adding the `globalcampus-signature` class to the body or html element successfully loads the inverted Global Campus signature when using `.crimson` on #spine.

![screen shot 2015-01-08 at 2 29 24 pm](https://cloud.githubusercontent.com/assets/5599170/5672131/c87c6126-9742-11e4-9c50-dbbf1af6fe5b.png)

**Comment by natejacobson** [comment]
Seeing as there has been no further clarification on this, and I wasn't able to reproduce the problem, I'm closing this. Feel free to reopen if necessary, @Toreybearly.
