### ISSUE TITLE
Different interior widths on guttered columns for thirds and quarters

### ISSUE THREAD

**Issue by natejacobson** [washingtonstateuniversity/WSU-spine#236]
In order to achieve equal gutters, first and last columns in thirds and quarters (interior and outer columns)  have both full and half width padding, while interior columns have half and half padding. This results in a discrepancy between the interior width (width minus padding) between columns. When trying to creating a row of images that are 100% width, for a staff profiles page for example, the images are not of equal size.

**Comment by natejacobson** [comment]
Additionally, there seems to be some jumping at certain widths where the floated halfs do not fit on one column, probably as a result of a rounding error where the column is 50.4% or some such.

**Comment by natejacobson** [comment]
A different approach to guttering: http://codepen.io/mofeenster/pen/vGgje.

**Comment by jeremyfelt** [comment]
Concerns raised by Joyce comparing stage.vcea.wsu.edu with vcea.wsu.edu and the new gutter technique.

* The Spine Parent Theme uses `guttered` in the main header. VCEA overrides the original padding, but does not yet have a rule to address the new borders. This may be somewhat common as we've never had an option for a gutterless/guttered main header in the parent theme, so sites would be forced to override specific rules.
* The first section on the home page is using the default `gutter` class that we assign in the parent theme, but is not overriding the padding that we set. Instead it's using absolute positioning, which the new border behavior is definitely having fun with. :)

**Comment by jeremyfelt** [comment]
The wsu.edu internal pages break in quite a few places as well, very much so in the main header due to `guttered`.

**Comment by jeremyfelt** [comment]
Fixed in #273 after #269 did not work out.
