### ISSUE TITLE
Focus issues with keyboard navigation

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSU-spine#237]
When navigating the Spine with a keyboard, focus on elements does not trigger the normal hover states. 

* Social/Contact/Print icons remain light, though the interactions still work when enter is hit.
* The indicator that a menu item has children does not appear when a parent is highlighted, though these items do have outlines.

**Comment by jeremyBass** [comment]
and we need to take https://github.com/washingtonstateuniversity/WSU-spine/issues/18 since this is apart of that.  Need a skip to nav  more so since it's under the content which makes tabbing a pain too.
