### ISSUE TITLE
Release next version of Spine

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSU-spine#268]
We should target April 14, 2015 for the next release of the Spine.

* What should the version be? Is this an enhancements and bugs only release (1.2.4) or a release with new features (1.3.0)?
* Is there anything specific to highlight in the changelog to sum up these commits? Is a general list enough? https://github.com/washingtonstateuniversity/WSU-spine/compare/1.2.3...develop

Any concerns around untested areas before release?

**Comment by jeremyfelt** [comment]
Chatted with @jeremyBass in @natejacobson, some conclusions:

* We're going to revert the recently added search panel handling, as some changes are needed and this will bump the feature version. This can go back into develop shortly after, though may also need a feature branch for a bit.
* We'd like to get #216 in for the next release, though if we aren't comfortable with how much testing can be done, we'll postpone it until 1.2.5 or 1.3.0.
* We need to do some more testing around the new gutter handling in the develop branch, but that should not hold up the shipping of 1.2.4 this week.

I'm going to change this milestone to 1.2.4 and that will be this week's target.

**Comment by jeremyfelt** [comment]
@natejacobson @jeremyBass - is 0690799b3d36c8061 the only commit needing revert for the search stuff?

**Comment by jeremyBass** [comment]
@jeremyfelt correct, I would think that the css stuff can stay @natejacobson would be better to speak to that

**Comment by jeremyBass** [comment]
@natejacobson per #216 here is a starter, not ideal consolidation, but it works in IE8+ , FF, Chrome, and Safari (win)

http://codepen.io/jeremyBass/pen/dPxGXv

**Comment by jeremyfelt** [comment]
@natejacobson left a comment on #236 with VCEA examples of breakage.

**Comment by jeremyfelt** [comment]
And we're shipped!
