### ISSUE TITLE
Health Sciences Spokane signature is clipped in Firefox

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSU-spine#279]
Current develop branch—OSX chrome, firefox, safari:

![screen shot 2015-04-16 at 10 16 21 am](https://cloud.githubusercontent.com/assets/286171/7186906/c2c84d86-e421-11e4-8616-048822b96c2b.png)

I'm not sure about blur, but it's definitely clipped in Firefox.

Smaller size, again with Chrome, Firefox, Safari:

![screen shot 2015-04-16 at 10 20 27 am](https://cloud.githubusercontent.com/assets/286171/7186971/4499e734-e422-11e4-86a3-769e3cbd5040.png)

University kind of looks like it's a rolling hill, especially in Chrome and Safari.

**Comment by erikafleck** [comment]
Hello, we have gone live with: http://medicalsciences.wsu.edu/ which uses the darker spine option. The Health Sciences logo would look sharp using white or at least lighter text with the darker option. Is this a possibility? 
![med_sci_screen](https://cloud.githubusercontent.com/assets/4030344/7420322/57c8c0be-ef30-11e4-869c-57c6249db7e6.jpg)

**Comment by jeremyfelt** [comment]
I'm not sure what happened, possibly a change in FireFox, but the Health Sciences Spokane mark is no longer clipping. I'm going to close this out, we can re-address if needed.
