### ISSUE TITLE
Search entry field is cutting off

### ISSUE THREAD

**Issue by MichelleFelt** [washingtonstateuniversity/WSU-spine#282]
The entry field is cut off on Windows 7 using Firefox (IE possibly, but I wasn't able to replicate it).

![screen shot 2015-04-29 at 9 08 30 am](https://cloud.githubusercontent.com/assets/6111174/7395615/dc663c34-ee4f-11e4-8348-965542e131eb.png)

**Comment by jeremyfelt** [comment]
This was reported again in Firefox. I was able to reproduce it in OSX on Firefox 36.0.4 and 38.0.5.

From the report: "Basically, the text input box for Search is floating up and overflowing the parent container. If I de-activate the Height attribute, it drops down and stops overflowing vertically. Not about the Submit button… that is still overflowing."

![searchboxerror](https://cloud.githubusercontent.com/assets/286171/8459018/46c6627e-1fcf-11e5-8410-4fa53ed48a40.png)
