### ISSUE TITLE
Font loading issues - Open Sans 300 wipes out 400

### ISSUE THREAD

**Issue by slocker3** [washingtonstateuniversity/WSU-spine#283]
On https://stage.future-student.ip.wsu.edu/wp-admin/customize.php?return=%2Fwp-admin%2Fupload.php when Open Sans 300 is selected it seems to make 400 disappear https://fonts.googleapis.com/css?family=Open+Sans%3A600%2C800%2C300%7COpen+Sans+Condensed%3A300%2C700&ver=4.2.2

**Comment by jeremyfelt** [comment]
This was a Spine Parent Theme issue, resolved in 0.20.3 via https://github.com/washingtonstateuniversity/WSUWP-spine-parent-theme/pull/208
