### ISSUE TITLE
More explicit defaults for base elements

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSU-spine#292]
It can be pretty easy to accidentally override the default styles of elements that we like to keep consistent as part of the Spine.

We should set more properties by default for at least `li` and `a` so that non-specific rulesets have a harder time changing the Spine itself.

**Comment by jeremyfelt** [comment]
Related https://web.wsu.edu/2015/06/06/styling-around-the-wsu-spine-with-custom-css/

**Comment by natejacobson** [comment]
Yes. Glad this is an issue. Can't hit it right now, but definitely needed.
