### ISSUE TITLE
overflow hidden?

### ISSUE THREAD

**Issue by sehill** [washingtonstateuniversity/WSU-spine#312]
I'm sure that at some point I was able to scroll horizontally, but now I notice that I can't.  Seems like jacket overflow:hidden was added at some point.  Any thoughts on how to allow scrolling?  As you can see, only part of the message gets through....

![untitled](https://cloud.githubusercontent.com/assets/7230560/10077482/4d7fbe86-6295-11e5-9fc8-0a1fb8c74ffc.png)

**Comment by jeremyBass** [comment]
The intended way to set up a page is to use the grid so that things will scale.  The image there should scale with it.  We would want to take a look at how that was set up to address this issue.  Shoot me an email if you would like help looking into it.
