### ISSUE TITLE
spine.min.css today 2016-03-30?

### ISSUE THREAD

**Issue by sehill** [washingtonstateuniversity/WSU-spine#362]
Did something change in //repo.wsu.edu/spine/1/spine.min.css today?  All of a sudden my colors are different and the spine won''t appear as unshelved on narrow browser windows or mobile devices.

I redirected to a locally saved copy of spine.min.css and everything works just fine again...Any advice is appreciated.    

With local version of spine.min.css here:    http://weather.wsu.edu
With repo version of spine.min.css here:  http://weather.prosser.wsu.edu

Best wishes--Sean

**Comment by jeremyfelt** [comment]
Hi @sehill, thanks for opening an issue.

We did push a new version of the Spine about an hour ago - https://github.com/washingtonstateuniversity/WSU-spine/releases/tag/1.4.0

A new version will be going out shortly that fixes #360 and #363, though I'm not sure if that will address all of the concerns at weather.wsu.edu. I'll take a closer look in a bit to see what's going on.

**Comment by jeremyfelt** [comment]
@sehill I think we've found the answer. Both the Spine CSS and JavaScript go hand in hand. It looks like weather.prosser.wsu.edu is using repo.wsu.edu to load spine.min.css, but calling the old version of the Spine JavaScript via http://weather.prosser.wsu.edu/include/scripts/spine.min.js.

I believe updating that JavaScript file will resolve most, if not all of the issues. I would recommend using repo.wsu.edu for that as well.

**Comment by sehill** [comment]
Great catch!  I wonder who (me) left that there..... Sorry for any additional work this put on you, and thank you for your support and efforts!  please consider this closed/non issue at this time...

**Comment by jeremyfelt** [comment]
Excellent, no worries at all! :)
