### ISSUE TITLE
Adjust the mobile menu icon

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSU-spine#371]
We'll be adjusting the mobile menu icon from three bars (:hamburger:) to two bars and the word "Menu" as the third bar.

We should probably go back to using an SVG vs the pseudo elements, but I'm not sure if we've thought much about that yet.

**Comment by natejacobson** [comment]
Okay. I really want to see this new icon :) Remember that going to an SVG makes animating the menu icon a bit trickier.

**Comment by jeremyfelt** [comment]
The chance that we do this as part of the Spine is approaching 0. Closing this for now. :)
