### ISSUE TITLE
Figures bleed outside of the column it's in.

### ISSUE THREAD

**Issue by clintyoung** [washingtonstateuniversity/WSU-spine#377]
Figures bleed over.

Example:
In WP, when I have a sidebar right and have an image with a caption (AKA a figure) it goes over into the other column.

**Comment by jeremyfelt** [comment]
We should be able to resolve this with the same `max-width: 100%;` rule that we use for images.

We'll want to add test markup in something like https://github.com/washingtonstateuniversity/WSU-spine/blob/develop/test/preprocess/content/content.html to help watch for breakage in the future.
