### ISSUE TITLE
html5.js is resource load error

### ISSUE THREAD

**Issue by charlesjdillon** [washingtonstateuniversity/WSU-spine#389]
It was pointed out to us that `http://html5shiv.googlecode.com/svn/trunk/html5.js` [https://github.com/washingtonstateuniversity/WSU-spine/blob/1d2417b3ca4efe8a0ef5c2343637b416bf39b836/test/preprocess/blocks/head.html#L56](https://github.com/washingtonstateuniversity/WSU-spine/blob/1d2417b3ca4efe8a0ef5c2343637b416bf39b836/test/preprocess/blocks/head.html#L56) is called into the Spine but it is not a supported link anymore. It may be causing resource load errors.

**Comment by jeremyfelt** [comment]
We can probably use https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js instead. This should only affect users on IE8 or lower.

**Comment by jeremyfelt** [comment]
We have this in quite a few places in addition to the sample markup in the Spine - https://github.com/search?q=org%3Awashingtonstateuniversity+https%3A%2F%2Fhtml5shiv.googlecode.com%2Fsvn%2Ftrunk%2Fhtml5.js&type=Code

**Comment by charlesjdillon** [comment]
Could it be done with a find a replace?

**Comment by jeremyfelt** [comment]
We'll need to fix on each repo and do a pull request with the change.
