### ISSUE TITLE
Need WSU sig with white lettering (crimson shield can remain) on gray Spine

### ISSUE THREAD

**Issue by slocker3** [washingtonstateuniversity/WSU-spine#392]
Example site: https://business.wsu.edu

**Comment by jeremyfelt** [comment]
It looks like we have a variant with crimson shield, gray chevron, and white text - https://github.com/washingtonstateuniversity/WSU-spine/blob/develop/marks/wsu-extension-signature-vertical-crimson-gray-white.svg

Would that work or should we create an alternate with crimson shield, white chevron, and white text?

If the we need a white chevron and white text, then we'll need to create new SVGs for horizontal/vertical for all of the location signatures. This looks like it wouldn't take too long as we're just changing a color.

This does make me wonder too if we still need the PNG fallbacks.

**Comment by jeremyfelt** [comment]
Going to go through the current config of each supported Spine color.

### Default (White) `#ffffff`

* Shield: `#981e31`
* Cougar: `#ffffff`
* Chevron: `#5e6a71`
* Text: `#5e6a71` (5.56:1 ratio, passes WCAG 2.0 AA)

### Dark `#3b4042`

* Shield: `#ffffff`
* Cougar: `#ffffff`
* Chevron: `#ffffff`
* Text: `#ffffff` (10.51:1 ratio, passes WCAG 2.0 AA)

### Darker `#23282b`

* Shield: `#981e31`
* Cougar: `#ffffff`
* Chevron: `#5e6a71`
* Text: `#5e6a71` (2.68:1 ratio, fails WCAG 2.0 AA)

### Crimson `#981e31`

* Shield: `#ffffff`
* Cougar: `#981e31`
* Chevron: `#ffffff`
* Text: `#ffffff` (8.19:1, passes WCAG 2.0AA)
