### ISSUE TITLE
Poor address typography (postal code)

### ISSUE THREAD

**Issue by mforbes** [washingtonstateuniversity/WSU-spine#393]
In the current CSS, there is no space or newline added between the `addressRegion` and the `postalCode` in the spin.  These elements should be styled appropriately so that the address in the spin looks good.  For example, the current contact part of the [spine test page](http://repo.wsu.edu/spine/develop/tests/columns.html) renders

```
University Unit
Washington State University
Your PO Box
Pullman, WA99164
```

There should at least be space and punctuation between the WA and the zip code, if not a new line:

```
University Unit
Washington State University
Your PO Box
Pullman, WA
99164
```

Also, what is the ``<span itemprop="location" content="Your location"></span>``?  It is not clear from the [schema](http://schema.org/Organization) what this should be.

Thanks.

**Comment by jeremyfelt** [comment]
Thanks @mforbes! We had this reported separately a little while ago for the [WSU Spine Parent Theme](https://github.com/washingtonstateuniversity/WSUWP-spine-parent-theme), but haven't addressed it anywhere.

I'll work on getting things updated in the repository. In the meantime, I think it's okay to add a space before the postal code `<span>` in any implementation as I think we'll use that rather than CSS to provide the space.

**Comment by jeremyfelt** [comment]
Oh, and:

> Also, what is the <span itemprop="location" content="Your location"></span>? It is not clear from the schema what this should be.

I'm not entirely sure. It seems like original intent was for a building name or something more casual.

**Comment by jeremyBass** [comment]
The  schema for `<span itemprop="location" content="Your location"></span>` is found at http://schema.org/location located which is an accepted value under http://schema.org/PostalAddress not http://schema.org/Organization and is what the whole block is under (PostalAddress that is)

Hope that helped to clear up the schema.  Cheers

**Comment by jeremyfelt** [comment]
> In the meantime, I think it's okay to add a space before the postal code <span> in any implementation as I think we'll use that rather than CSS to provide the space.

I just remembered that the Spine itself is using JS to create this HTML. We'll get an update shipped shortly.
