### ISSUE TITLE
Add lookup for custom share text

### ISSUE THREAD

**Issue by natejacobson** [washingtonstateuniversity/WSU-spine#50]
We need to add the option to use a custom share text string for twitter especially, and perhaps for other social networks. The js might look something like this, but I'm struggling to make such a change in the new, advanced Spine javascript.

	if ( $('meta[name="share-text-twitter"]').length ) {
			var share_text_twitter = $('meta[name="share-text-twitter"]').attr('content');
		} elseif ( $('meta[name="share-text"]').length ) { 
			var share_text_general = $('meta[name="share-text"]').attr('content');
		} else {
			var share_text_general = "I discovered ...";
		}
	$.extend($.ui.spine.prototype, {
		social_init: function(options) {
			//alert('init social');
			//alert("options==>"+dump(options));
			$.extend(this.social_options,options);
			//alert("options==>"+dump(this.social_options));
			this._set_globals(this.social_globals);
			this.social_create();
		},
		social_options:{
			provider:"WSU_share",
			script_url:"//repo.wsu.edu/wsu_share/1/",
			channels:[
				"facebook",
				"twitter",
				"pinterest"
			],
			share_text: $share_text_general,
			share_text_twitter: $share_text_twitter,
		},

**Comment by jeremyfelt** [comment]
This was effectively "temporarily" fixed in #229. We may want to make things better in the future, but it's been working for over a year.
