### ISSUE TITLE
Blurred SVG at small screen size in Firefox

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSU-spine#61]
Firefox in Windows 7 with the background size set to 260px per the media query in [respond.css#l648](https://github.com/washingtonstateuniversity/WSU-spine/blob/1c1817e35524b024e7d596581dbbaec29bd8acc3/styles/respond.css#L648)
![260px-bgsize](https://cloud.githubusercontent.com/assets/286171/2699338/426243aa-c405-11e3-9c5a-35e427198cac.png)

Things get a little less blurry if you change the background size to 258px. 261px also works a bit.
![258px-bgsize](https://cloud.githubusercontent.com/assets/286171/2699354/8a09ce6c-c405-11e3-81a1-1797667e0494.png)
![261px-bgsize](https://cloud.githubusercontent.com/assets/286171/2699356/8be670e6-c405-11e3-86be-fbeab112c24a.png)

However, IE 10 loves 260px and is as sharp as Chrome:
![allbrowsers](https://cloud.githubusercontent.com/assets/286171/2699368/a94cfb0a-c405-11e3-9ad5-659f47c78c68.png)

If the background size is changed to 258px or 261px, IE gets blurry, Chrome stays the same, and Firefox gets slightly better.

Guessing this is a wontfix as I haven't seen this on mobile yet, where it would matter most, and it appears to only directly affect Firefox in Windows (OSX is fine). It's worth being aware of though, as the SVG size seems to matter very much at that level.

**Comment by natejacobson** [comment]
The blur is back: cf. invested.spokane.wsu.edu.

**Comment by slocker3** [comment]
Spokane has reported issues with the blurring of the signatures in multiple devices/systems. I agree that it is an issue -- example site, http://extra.spokane.wsu.edu/, it might have a lot to do with the Spine color. http://invested.spokane.wsu.edu/ looks better.

**Comment by natejacobson** [comment]
Yes. The fine lines are blurring, in all browsers. With the size of the campus text, a pixel perfect .png rendering may be necessary.

**Comment by jeremyBass** [comment]
Have we already gone thought the starting size fix we talked about?

**Comment by natejacobson** [comment]
What I think we need to know before proceeding is whether the issue raised is something specific to our html/css/svg implementation or rather inherent to the trying to present our signature at the size we are, especially on a crimson background. Are people experiencing fuzziness as seen in the rasterized image below, or something worse?
![hsspokane-on-crimson](https://cloud.githubusercontent.com/assets/5599170/6467721/db8f65f8-c184-11e4-8398-0f280b6bcae4.png)

**Comment by natejacobson** [comment]
I don't know why I didn't think of this, but we could also address the thinness of the typeface in the small vertical logo by adding a stroke to the text. Here's an attempt with a .3pt stroke on the logotype and campus text. Better?
![screen shot 2015-03-03 at 11 56 05 am](https://cloud.githubusercontent.com/assets/5599170/6471291/78d52668-c19e-11e4-85eb-a182f11f976f.png)

**Comment by jeremyBass** [comment]
@natejacobson is this set now and done?

**Comment by jeremyfelt** [comment]
This came up again on a call with Spokane yesterday. I can't tell via commits that this has been addressed.

Current develop branch—OSX chrome, firefox, safari:

![screen shot 2015-04-16 at 10 16 21 am](https://cloud.githubusercontent.com/assets/286171/7186906/c2c84d86-e421-11e4-8616-048822b96c2b.png)

I'm not sure about blur, but it's definitely clipped in Firefox.

Smaller size, again with Chrome, Firefox, Safari:

![screen shot 2015-04-16 at 10 20 27 am](https://cloud.githubusercontent.com/assets/286171/7186971/4499e734-e422-11e4-86a3-769e3cbd5040.png)

University kind of looks like it's a rolling hill, especially in Chrome and Safari.

**Comment by jeremyfelt** [comment]
I think our original blurring issues are solved. I'm going to move this discussion to a new issue because clipping definitely exists in the Health Sciences signature.

**Comment by jeremyfelt** [comment]
See #279 for continued Health Sciences work.
