### ISSUE TITLE
.NET + mobile

### ISSUE THREAD

**Issue by richardblink** [washingtonstateuniversity/WSU-spine#65]
I am experiencing an issue.  If I take spine.html and put form tags just inside of the body tags for use as a master page in our site, the fly-out menu (for the smaller breakpoints) stops working.  Suggestions? Fixes?

**Comment by jeremyfelt** [comment]
I'm going to toss in the `type="button"` fix. I missed that comment so many times when reading this issue before. It does not appear to impact anything else. Sorry for the 2 year wait. :sweat_smile:
