### ISSUE TITLE
Non-semantic use of <sup> and <sub> in .main-header

### ISSUE THREAD

**Issue by doingweb** [washingtonstateuniversity/WSU-spine#98]
[The HTML5 spec](http://www.w3.org/TR/html5/text-level-semantics.html#the-sub-and-sup-elements) prescribes that `<sup>` and `<sub>` be used only for specific "typographical conventions", such as abbreviations where the language calls for it, or mathematical expressions:

> These elements must be used only to mark up typographical conventions with specific meanings, not for typographical presentation for presentation's sake. [...] In general, authors should use these elements only if the absence of those elements would change the meaning of the content.

The Spine [currently uses `<sup>` and `<sub>`](https://github.com/washingtonstateuniversity/WSU-spine/blob/master/styles/sass/skeleton.scss#L237) to markup the [main header for the page](https://github.com/washingtonstateuniversity/WSU-spine/wiki/II.1.-Page:-Structure). It would be more semantic to either use [proper headings](http://html5doctor.com/howto-subheadings/) (e.g., `<h1>`, `<h2>`, etc.) if it makes sense for it to be in the document outline, or plain `<p>` elements.

**Comment by jeremyfelt** [comment]
The discussion on this thread was good. At this point, we're committed. :)
